# Generated by Django 2.1.11 on 2020-02-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_module_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RoomProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='has_problem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomproblem',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RoomProblemType'),
        ),
        migrations.AddField(
            model_name='roomproblem',
            name='room_concerned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Room'),
        ),
    ]
