# Generated by Django 2.1.15 on 2020-02-28 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200227_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomproblem',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomproblemtype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
