# Generated by Django 3.0.5 on 2020-04-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_room_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_problem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoomProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='RoomProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
                ('problem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RoomProblemType')),
                ('room_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='base.Building'),
        ),
    ]
