version: '3.8'

services:
  db:
    image: postgres
    profiles:
      - full
    environment:
      PGDATA: /var/lib/postgresql/data/flopedt-${BRANCH:-master}
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:latest
    profiles:
      - full
    ports:
      - "${REDIS_PORT-6379}:6379"

  backend:
    build:
      context: .
      args:
        CONFIG: development
    profiles:
      - full
    env_file: 
      - ./docker/env/db.env
      - ./docker/env/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=FlOpEDT.settings.development
      - START_SERVER=${START_SERVER:-on}
      - DJANGO_LOADDATA=off
      - DJANGO_FLUSHDATA=off
      - CONFIG=development
    entrypoint: /code/docker/script/init.sh      
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  vue:
    build:
      dockerfile: ./Dockerfile-Vue
    profiles:
      - full
    environment:
      - CONFIG=development
    volumes:
      - ./FlOpEDT-front:/front
    network_mode: "host"
    ports:
      - "5173:5173"
    entrypoint: ["yarn", "dev"]
