# Generated by Django 3.0.14 on 2022-02-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTapp', '0058_auto_20220222_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoidbothtimes',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='considertutorsunavailability',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='curfew',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='customconstraint',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='limitholes',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='limitsimultaneouscoursesnumber',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='limittutorstimeperperiod',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='limittutortimeperweeks',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='limitundesiredslotsperweek',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='lowerboundbusydays',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='minimizebusydays',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='minnonpreferedtutorsslot',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='mintutorshalfdays',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='notutorcourseonday',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='respectboundperday',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='simultaneouscourses',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='stabilizationthroughweeks',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='stabilizetutorscourses',
            name='train_progs',
        ),
        migrations.RemoveField(
            model_name='tutorslunchbreak',
            name='train_progs',
        ),
    ]
